import dotenv from "dotenv";
dotenv.config();

const MONGO_URI = process.env.MONGODB_URI;
const PORT = process.env.PORT;
const TOKEN_SECRET = process.env.TOKEN_SECRET;
const GOOGLE_APPLICATION_CREDENTIALS =
  process.env.GOOGLE_APPLICATION_CREDENTIALS;
const GOOGLE_APLICATION_CREDENTIALS_STRING =
  process.env.GOOGLE_APLICATION_CREDENTIALS_STRING;

export {
  MONGO_URI,
  PORT,
  TOKEN_SECRET,
  GOOGLE_APPLICATION_CREDENTIALS,
  GOOGLE_APLICATION_CREDENTIALS_STRING,
};
